name: pymc-examples
channels:
- conda-forge
- defaults
dependencies:
# Base dependencies
- black
- codespell
- ipython
- jupyterlab
- notebook
- pandas
- pre-commit>=2.8.0
- pymc
- watermark
# Extra dependencies for docs build
- ablog>=0.11
- matplotlib
- myst-nb
- sphinx-codeautolink
- sphinx>=5
- pymc-sphinx-theme==0.14
- sphinx-copybutton
- sphinx-design
- sphinx-notfound-page
- sphinxcontrib-bibtex
- sphinxext-opengraph
- sphinxext-rediraffe
- sphinx-sitemap
